sudo: required

dist: trusty

services:
  - docker

env:
  global:
    - IMAGE_NAME=rohanmengade/game-dashboard

language: java

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk11

os:
  - linux

install:
  - mvn clean install

script:
  - mvn clean package


before_deploy:
  # create a docker image tag for develop branch
  - if [[ $TRAVIS_BRANCH == "develop" ]]; then export IMAGE_TAG=$TRAVIS_BUILD_NUMBER-dev; fi
  # create a docker image tag for master branch
  - if [[ $TRAVIS_BRANCH =~ master.* ]]; then export IMAGE_TAG=$TRAVIS_BUILD_NUMBER-master; fi
  # create a docker image tag for git tags
  - if [[ $TRAVIS_TAG ]]; then export IMAGE_TAG=$TRAVIS_TAG; fi
  - docker build -t "$IMAGE_NAME" .
  - docker tag "$IMAGE_NAME" "$IMAGE_NAME:$IMAGE_TAG"
  - echo "$DOCKER_PASSWORD" | docker login docker.io -u "$DOCKER_USERNAME" --password-stdin


deploy:
  # create docker image for develop or release branches
  - provider: script
    skip_cleanup: true
    script: docker push "${IMAGE_NAME}:${IMAGE_TAG}"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^develop|master.*
  # create docker image for tags
  - provider: script
    skip_cleanup: true
    script: docker push "${IMAGE_NAME}:${IMAGE_TAG}"
    on:
      tags: true


